#端口号配置
server:
  address: 0.0.0.0
  port: 8089
#数据库连接配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/canteen_lib?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

#mybatis plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #配置mybatis plus 在更新时只更新非NULL的字段
      update-strategy: not_empty
# 菜品图片上传
web:
  uploadpath: E:/DishImages/
  load-path: file:E:/DishImages/

  # 微信小程序相关
  Wechat:
    Applets:
      # 小程序appID
      appId: wx05eda073665c9384
      # 小程序秘钥
      appSecret: 362870028db018bc2a0cf1081bf68763


logging:
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger - %msg%n'
